local ActivityEvent = {}

ActivityEvent.ACTEVENT_FINISH_TASK_OK = "ACTEVENT_FINISH_TASK_OK"

ActivityEvent.ACTEVENT_KAIFU_QIANGGOU_DATA = "ACTEVENT_KAIFU_QIANGGOU_DATA"

ActivityEvent.ACTEVENT_FULI_RED_EVENT = "ACTEVENT_FULI_RED_EVENT"

ActivityEvent.ACTEVENT_CONDITION_NUMCHANGE_EVENT = "ACTEVENT_CONDITION_NUMCHANGE_EVENT"

ActivityEvent.ACTEVENT_KAIFU_TIMEOVER = "ACTEVENT_KAIFU_TIMEOVER"

ActivityEvent.ACTEVENT_RETRIEVE_ITEM = "ACTEVENT_RETRIEVE_ITEM"

-- 触发六界游商
ActivityEvent.TRRIGER_WANDER_MERCHANT = "TRRIGER_WANDER_MERCHANT"
-- 倒计时结束,小额充值关闭
ActivityEvent.ONE_ACT_TIME_OVER = "ONE_ACT_TIME_OVER"
--活动界面红点刷新事件
ActivityEvent.REFRESH_RED_POINT = "ActivityEvent.REFRESH_RED_POINT"

--六界游商抽折扣 刷新游商界面的现价
ActivityEvent.TRAVELSHOP_TAKE_DISCOUNT_ENENT = "TRAVELSHOP_TAKE_DISCOUNT_ENENT"

ActivityEvent.TRAVELSHOP_PLAY_ANIMATION_EVENT = "TRAVELSHOP_PLAY_ANIMATION_EVENT"

-- 六界游商结束 关闭抽折扣界面
ActivityEvent.TRAVELSHOP_TIME_IS_OVER_EVENT = "TRAVELSHOP_TIME_IS_OVER_EVENT"


ActivityEvent.ACTEVENT_KAIFU_QIANGGOU_REFRESH_RED = "ACTEVENT_KAIFU_QIANGGOU_REFRESH_RED"

ActivityEvent.TRAVELSHOP_REFRESH_BUYBTN_STATUS = "TRAVELSHOP_REFRESH_BUYBTN_STATUS"

ActivityEvent.ACTEVENT_EVENTDAYTASK_REFRESH_RED = "ACTEVENT_EVENTDAYTASK_REFRESH_RED"

return ActivityEvent
