local ArtifactEvent = {}
-- 监听事件
-- ArtifactEvent.ACTEVENT_FINISH_TASK_OK = "ACTEVENT_FINISH_TASK_OK" 
ArtifactEvent.ACTEVENT_SINGLE_ADVANCED = "ACTEVENT_SINGLE_ADVANCED"  --单个进阶
ArtifactEvent.ACTEVENT_COMBINATION_ADVANCED = "ACTEVENT_COMBINATION_ADVANCED"--组合进阶
ArtifactEvent.ACTEVENT_DECOMPOSITION = "ACTEVENT_DECOMPOSITION"   --分解
ArtifactEvent.ACTEVENT_CHOUKA_CALLBACK = "ACTEVENT_CHOUKA_CALLBACK"  ---抽卡回调
ArtifactEvent.ACTEVENT_CHOUKA_BACK_IN_UI = "ACTEVENT_CHOUKA_BACK_IN_UI" --抽卡奖励界面返回到抽奖界面回调
ArtifactEvent.DECOMPOSE_REFRESH_UI = "DECOMPOSE_REFRESH_UI"  --分解后刷新界面
ArtifactEvent.CLOSE_TO_UI = "CLOSE_TO_UI" --退出抽卡界面
ArtifactEvent.ACTEVENT_TOWER_FLOOR_EVENT = "ACTEVENT_TOWER_FLOOR_EVENT" --退出抽卡界面


return ArtifactEvent
