
local GarmentEvent = {}

--买衣服
GarmentEvent.GARMENT_BUY_SUCCESS_EVENT = "GARMENT_BUY_SUCCESS_EVENT"

--穿衣服
GarmentEvent.GARMENT_ON_SUCCESS_EVENT = "GARMENT_ON_SUCCESS_EVENT"

--衣服时间到了
GarmentEvent.GARMENT_ON_TIME_UP = "GARMENT_ON_TIME_UP"

--换衣服
GarmentEvent.GARMENT_CHANGE_ONE = "GARMENT_CHANGE_ONE"

--显示分享UI
GarmentEvent.GARMENT_SHARE_UI = "GARMENT_SHARE_UI"

--关闭分享UI
GarmentEvent.GARMENT_CLOSE_SHARE_UI = "GARMENT_CLOSE_SHARE_UI"

GarmentEvent.GARMENT_CLOSE_MAIN_UI = "GARMENT_CLOSE_MAIN_UI"

--服务器时装数据发生变化
GarmentEvent.GARMENT_SERVER_DATA_CHANGE = "GARMENT_SERVER_DATA_CHANGE"

return GarmentEvent