--
--Author:      zhuguangyuan
--DateTime:    2017-10-21 15:49:21
--Description: 仙盟GVE活动事件
--

local GuildActivityEvent = {}

-- 活动开启
GuildActivityEvent.GUILD_ACTIVITY_EVENT_ONE_ACTIVITY_OPEN = "GUILD_ACTIVITY_EVENT_ONE_ACTIVITY_OPEN"

-- 创建队伍成功
GuildActivityEvent.GUILD_ACTIVITY_EVENT_TEAM_CREATE_SUCCEED = "GUILD_ACTIVITY_EVENT_TEAM_CREATE_SUCCEED"
-- 加入队伍成功
GuildActivityEvent.GUILD_ACTIVITY_EVENT_JOIN_TEAM_SUCCEED = "GUILD_ACTIVITY_EVENT_JOIN_TEAM_SUCCEED"
-- 离开队伍成功
GuildActivityEvent.GUILD_ACTIVITY_EVENT_LEAVE_TEAM_SUCCEED = "GUILD_ACTIVITY_EVENT_LEAVE_TEAM_SUCCEED"
-- 确认离开队伍
GuildActivityEvent.GUILD_ACTIVITY_EVENT_LEAVE_TEAM_CONFIRM = "GUILD_ACTIVITY_EVENT_LEAVE_TEAM_CONFIRM"

-- 队员发生变化
GuildActivityEvent.GUILD_ACTIVITY_EVENT_TEAM_MEMBERS_CHANGE = "GUILD_ACTIVITY_EVENT_TEAM_MEMBERS_CHANGE"

-- 开始挑战
GuildActivityEvent.GUILD_ACTIVITY_EVENT_TEAM_START_CHALLENGE = "GUILD_ACTIVITY_EVENT_TEAM_START_CHALLENGE"


-- 标记怪
GuildActivityEvent.GUILD_ACTIVITY_EVENT_TEAM_MARK_MONSTER = "GUILD_ACTIVITY_EVENT_TEAM_MARK_MONSTER"
-- 取消标记怪
GuildActivityEvent.GUILD_ACTIVITY_EVENT_TEAM_UNMARK_MONSTER = "GUILD_ACTIVITY_EVENT_TEAM_UNMARK_MONSTER"



-- 某人打败了怪物
GuildActivityEvent.GUILD_ACTIVITY_EVENT_TEAM_SOMEONE_DEFEAT_MONSTER = "GUILD_ACTIVITY_EVENT_TEAM_SOMEONE_DEFEAT_MONSTER"
-- 一轮战斗结算数据更新完成，开始移动并补充新怪
GuildActivityEvent.GUILD_ACTIVITY_EVENT_TEAM_ACCOUNT_DATA_READY = "GUILD_ACTIVITY_EVENT_TEAM_ACCOUNT_DATA_READY"
-- 五轮后的结算
GuildActivityEvent.GUILD_ACTIVITY_EVENT_LAST_ROUND_FIFISHED = "GUILD_ACTIVITY_EVENT_LAST_ROUND_FIFISHED"

-- 某人投入了食材
GuildActivityEvent.GUILD_ACTIVITY_EVENT_SOMEONE_INPUT_INGREDIENTS = "GUILD_ACTIVITY_EVENT_SOMEONE_INPUT_INGREDIENTS"
-- 被踢
GuildActivityEvent.GUILD_ACTIVITY_EVENT_BE_KICKOUT_BY_TEAMLEADER = "GUILD_ACTIVITY_EVENT_BE_KICKOUT_BY_TEAMLEADER"
-- 领取奖励
GuildActivityEvent.GUILD_ACTIVITY_EVENT_GOT_REWARD = "GUILD_ACTIVITY_EVENT_GOT_REWARD"


-- 某人放弃挑战
GuildActivityEvent.GUILD_ACTIVITY_EVENT_SOMEONE_QUIT = "GUILD_ACTIVITY_EVENT_SOMEONE_QUIT"

-- 刷新时间到
GuildActivityEvent.GUILD_ACTIVITY_EVENT_ACCOUNT_TIME_UP = "GUILD_ACTIVITY_EVENT_ACCOUNT_TIME_UP"
-- 周积分奖励到期
GuildActivityEvent.GUILD_ACTIVITY_EVENT_ACCOUNT_TIME_UP_WEEK = "GUILD_ACTIVITY_EVENT_ACCOUNT_TIME_UP_WEEK"

-- 挑战正常结束
GuildActivityEvent.GUILD_ACTIVITY_EVENT_CHALLENGE_END = "GUILD_ACTIVITY_EVENT_CHALLENGE_END"

-- 校验错误 强制同步到服务器数据
GuildActivityEvent.GUILD_ACTIVITY_EVENT_CHECK_SIM_ERROR = "GUILD_ACTIVITY_EVENT_CHECK_SIM_ERROR"



-- 食材数量发生变化
GuildActivityEvent.GUILD_ACTIVITY_EVENT_MATERIAL_NUM_CHANGE = "GUILD_ACTIVITY_EVENT_MATERIAL_NUM_CHANGE"

-- 一只队伍解散了 发送加入队伍请求返回错误码 为 560901
GuildActivityEvent.GUILD_ACTIVITY_ONE_TEAM_DISMISS = "GUILD_ACTIVITY_ONE_TEAM_DISMISS"

-- 重连时队伍已经挑战结束 关闭挑战场景界面 更新gve信息
GuildActivityEvent.GUILD_ACTIVITY_CLOSE_INTERACT_VIEW = "GUILD_ACTIVITY_CLOSE_INTERACT_VIEW"

-- 模拟教学关卡
-- 触发引导者说话
GuildActivityEvent.GUILD_ACTIVITY_GUIDE_TRIGGER_INDUCTOR_EXPLAIN = "GUILD_ACTIVITY_GUIDE_TRIGGER_INDUCTOR_EXPLAIN"
-- 引导者说话完毕 或者倒计时结束 触发combo
GuildActivityEvent.GUILD_ACTIVITY_GUIDE_TRIGGER_COMBO = "GUILD_ACTIVITY_GUIDE_TRIGGER_COMBO"
-- 引导完毕 引导者说明完毕 触发恭喜获得引导奖励
GuildActivityEvent.GUILD_ACTIVITY_GUIDE_TRIGGER_REWARD = "GUILD_ACTIVITY_GUIDE_TRIGGER_REWARD"

return GuildActivityEvent