--家园系统相关事件
local GuildEvent = {}
--[[
--创建
GuildEvent.CREATE_GUILD_EVENT = "CREATE_GUILD_EVENT";


--查询
GuildEvent.FIND_GUILD_EVENT = "FIND_GUILD_EVENT";
GuildEvent.FIND_GUILD_OK_EVENT = "FIND_GUILD_OK_EVENT";

--列表
GuildEvent.LIST_GUILD_EVENT = "LIST_GUILD_EVENT";
GuildEvent.LIST_GUILD_OK_EVENT = "LIST_GUILD_OK_EVENT";

--关闭GuildBlankView 
GuildEvent.CLOSE_GUILD_BLANK_VIEW_EVENT = "CLOSE_GUILD_BLANK_VIEW_EVENT";
GuildEvent.CLOSE_GUILD_JOIN_VIEW_EVENT = "CLOSE_GUILD_JOIN_VIEW_EVENT";


--申请加入公会
GuildEvent.GUILD_APPLY_EVENT = "GUILD_APPLY_EVENT";
GuildEvent.GUILD_APPLY_OK_EVENT = "GUILD_APPLY_OK_EVENT";

--公会成员信息
GuildEvent.GUILD_GET_MEMBERS_EVENT = "GUILD_GET_MEMBERS_EVENT";
GuildEvent.GUILD_GET_MEMBERS_OK_EVENT = "GUILD_GET_MEMBERS_OK_EVENT";

--公会申请列表
GuildEvent.GUILD_GET_APPLY_LIST_EVENT = "GUILD_GET_APPLY_LIST_EVENT";
GuildEvent.GUILD_GET_APPLY_LIST_OK_EVENT = "GUILD_GET_APPLY_LIST_OK_EVENT";

--修改公会配置
GuildEvent.GUILD_MODITY_CONFIG_EVENT = "GUILD_MODITY_CONFIG_EVENT";
GuildEvent.GUILD_MODITY_CONFIG_OK_EVENT = "GUILD_MODITY_CONFIG_OK_EVENT";

--取消公会申请
GuildEvent.GUILD_CANCEL_APPLY_EVENT = "GUILD_CANCEL_APPLY_EVENT";
GuildEvent.GUILD_CANCEL_APPLY_OK_EVENT = "GUILD_CANCEL_APPLY_OK_EVENT";

--公会成员发生变化
GuildEvent.GUILD_MEMBER_CHANGE_EVENT = "GUILD_MEMBER_CHANGE_EVENT";

--入会审批
GuildEvent.GUILD_APPLY_JUDGE_EVENT = "GUILD_APPLY_JUDGE_EVENT";
GuildEvent.GUILD_APPLY_JUDGE_OK_EVENT = "GUILD_APPLY_JUDGE_OK_EVENT";

--退出公会
GuildEvent.GUILD_KICK_GUILD_EVENT = "GUILD_KICK_GUILD_EVENT";
GuildEvent.GUILD_KICK_GUILD_OK_EVENT = "GUILD_KICK_GUILD_OK_EVENT";

--修改会员权限
GuildEvent.GUILD_MODIFY_MEMBER_RIGHT_EVENT = "GUILD_MODIFY_MEMBER_RIGHT_EVENT";
GuildEvent.GUILD_MODIFY_MEMBER_RIGHT_OK_EVENT = "GUILD_MODIFY_MEMBER_RIGHT_OK_EVENT";

--退出公会
GuildEvent.GUILD_QUIT_EVENT = "GUILD_QUIT_EVENT";
GuildEvent.GUILD_QUIT_OK_EVENT = "GUILD_QUIT_OK_EVENT";


GuildEvent.GUILD_invite_OK_EVENT = "GUILD_invite_OK_EVENT";
--]]

--返回到创建界面的第一个界面
GuildEvent.BREAK_CREATE_TO_UI = "BREAK_CREATE_TO_UI"


--跳转到推荐申请加入公会
GuildEvent.GUILD_jump_TO_RECOMMEND = "GUILD_jump_TO_RECOMMEND";
GuildEvent.GUILD_REFRESH_ICON = "GUILD_REFRESH_ICON";
	
--主界面显示玩家
GuildEvent.SHOW_RES_COMING_ANI = "SHOW_RES_COMING_ANI";

--公告修改
GuildEvent.AMEND_STR_EVENT = "AMEND_STR_EVENT";

--领取祈福
GuildEvent.GET_QIFU_REWARD = "GET_QIFU_REWARD";
--刷新心愿列表
GuildEvent.REFRESH_WISH_LIST_EVENT = "REFRESH_WISH_LIST_EVENT";

--刷新成员列表事件
GuildEvent.REFRESH_MEMBERS_LIST_EVENT = "REFRESH_MEMBERS_LIST_EVENT";

--刷新灵木资源
GuildEvent.REFRESH_GUILD_WOOD_EVENT = "REFRESH_GUILD_WOOD_EVENT";
GuildEvent.REFRESH_GUILD_RESOURCE_EVENT = "REFRESH_GUILD_RESOURCE_EVENT";

--刷新建设
GuildEvent.REFRESH_GUILD_BUILD_EVENT = "REFRESH_GUILD_BUILD_EVENT";

GuildEvent.CLOSE_ADD_GUILD_VIEW_EVENT = "CLOSE_ADD_GUILD_VIEW_EVENT";

---退出所有界面
GuildEvent.CLOSE_ALL_VIEW_EVENT = "CLOSE_ALL_VIEW_EVENT";

--退出详情界面
GuildEvent.CLOSE_INFO_VIEW_EVENT = "CLOSE_INFO_VIEW_EVENT";

--- 签到
GuildEvent.REFRESH_SIGN_EVENT = "REFRESH_SIGN_EVENT";
---红利
GuildEvent.REFRESH_BOUNS_EVENT = "REFRESH_BOUNS_EVENT";

--创建公会
GuildEvent.CREATE_GUILD_OK_EVENT = "CREATE_GUILD_OK_EVENT";

--邀请
GuildEvent.GUILD_invite_EVENT = "GUILD_invite_EVENT";

--刷新邀请界面
GuildEvent.GUILD_REFRESH_invite_EVENT = "GUILD_REFRESH_invite_EVENT";

--刷新灵木数量
GuildEvent.GUILD_REFRESH_WOOD_EVENT = "GUILD_REFRESH_WOOD_EVENT";

--时间到了四点，刷新
GuildEvent.GUILD_ONTIME_REFRESH_UI = "GUILD_ONTIME_REFRESH_UI";

GuildEvent.GUILD_REMOVE_REFRESH_UI = "GUILD_REMOVE_REFRESH_UI";

GuildEvent.CLOSE_ALL_VIEW_UI = "CLOSE_ALL_VIEW_UI"; 

GuildEvent.GUILD_AGREEANDNOTA_UI = "GUILD_AGREEANDNOTA_UI";

GuildEvent.GUILD_REFRESH_BOX_EVENT = "GUILD_REFRESH_BOX_EVENT";
--被剔除仙盟
GuildEvent.GUILD_QUILT_EVENT = "GUILD_QUILT_EVENT";

-- gve或者副本红点发生改变
GuildEvent.GUILD_ACTIVITY_REDPOINT_CHANGED = "GUILD_ACTIVITY_REDPOINT_CHANGED";


GuildEvent.GUILD_EXCHANGE_LIST_FRESH = "GUILD_EXCHANGE_LIST_FRESH";

--刷新收集界面的数据
GuildEvent.GUILD_SHOUJI_LIST_REFRESH = "GUILD_SHOUJI_LIST_REFRESH";
--显示我的红包
GuildEvent.GUILD_REDPACKET_SHOW_MY = "GUILD_REDPACKET_SHOW_MY";

--显示仙盟红包
GuildEvent.GUILD_REDPACKET_SHOW = "GUILD_REDPACKET_SHOW";

--显示红包红点问题
GuildEvent.GUILD_REDPACKET_SHOW_RED = "GUILD_REDPACKET_SHOW_RED";

-- 精研成功 通知刷新界面
GuildEvent.GUILD_THEME_LEVEL_UP_SUCCEED = "GUILD_THEME_LEVEL_UP_SUCCEED"

GuildEvent.SHOW_APPLIST_VIEW = "SHOW_APPLIST_VIEW";
GuildEvent.SHOW_MEMBLE_VIEW = "SHOW_MEMBLE_VIEW";


GuildEvent.REFRESH_TASK_RED_UI = "REFRESH_TASK_RED_UI";

GuildEvent.REFRESH_UI = "REFRESH_UI";

GuildEvent.REFRESH_DIGTOOLNUM = "REFRESH_DIGTOOLNUM";

GuildEvent.REFRESH_TREASURE_MAIN_VIEW = "REFRESH_TREASURE_MAIN_VIEW";

GuildEvent.REFRESH_DIG_MAP_MAIN_VIEW = "REFRESH_DIG_MAP_MAIN_VIEW";

return GuildEvent







