--
-- Author: lxh
-- Date: 2017-10-19

local GuildBossEvent = {}

GuildBossEvent.SHAREBOSS_NUM_CHANGED = "SHAREBOSS_NUM_CHANGED"
GuildBossEvent.COUNT_TYPE_SHAREBOSS_TRIGGER = "COUNT_TYPE_SHAREBOSS_TRIGGER"
GuildBossEvent.SHAREBOSS_DATA_CHANGED = "SHAREBOSS_DATA_CHANGED"
GuildBossEvent.SHAREBOSS_RANK_DATA_CHANGED = "SHAREBOSS_RANK_DATA_CHANGED"
GuildBossEvent.SHAREBOSS_CHALLENGE_RESET = "SHAREBOSS_CHALLENGE_RESET"

-- 仙盟boss数据有变动
GuildBossEvent.GUILDBOSS_DATA_UPDATE = "GUILDBOSS_DATA_UPDATE"
-- 副本通关成功
GuildBossEvent.GUILDBOSS_ONE_ECTYPE_PASS = "GUILDBOSS_ONE_ECTYPE_PASS"
-- 定时器时间到
GuildBossEvent.GUILDBOSS_TIMER_RESET_DAY_COUNT = "GUILDBOSS_TIMER_RESET_DAY_COUNT"
GuildBossEvent.GUILDBOSS_TIMER_ECTYPE_TIME_OUT = "GUILDBOSS_TIMER_ECTYPE_TIME_OUT"
-- 一个副本开启
GuildBossEvent.GUILDBOSS_ONE_ECTYPE_OPEN = "GUILDBOSS_ONE_ECTYPE_OPEN"

GuildBossEvent.GUILDBOSS_REFRESH_BOSS_HP = "GUILDBOSS_REFRESH_BOSS_HP"


GuildBossEvent.GUILDBOSS_REFRESH_BOSS_RED = "GUILDBOSS_REFRESH_BOSS_RED"

GuildBossEvent.GUILDBOSS_CLOSE_OPEN_VIEW = "GUILDBOSS_CLOSE_OPEN_VIEW"


--移除其他玩家数据
GuildBossEvent.REMOVE_OTHER_DATA = "REMOVE_OTHER_DATA"
--关闭邀请界面
GuildBossEvent.CLOSE_INVITE_VIEW = "GuildBossEvent.CLOSE_INVITE_VIEW"


return GuildBossEvent
