--
-- Author: xd
-- Date: 2018-07-03 11:31:56
--

local GuildExploreEvent = {}

--资源发生变化
GuildExploreEvent.RES_EXCHANGE_REFRESH = "RES_EXCHANGE_REFRESH"


--矿洞初始化完成
GuildExploreEvent.GUILDEXPLOREEVENT_INITCOMPLETE = "GUILDEXPLOREEVENT_INITCOMPLETE"

--有玩家数据发生变化 对应阵营1  2
GuildExploreEvent.GUILDEXPLOREEVENT_USERDATACHANGE = "GUILDEXPLOREEVENT_USERDATACHANGE"

--用户离开
GuildExploreEvent.GUILDEXPLOREEVENT_USERLEAVE = "GUILDEXPLOREEVENT_USERLEAVE"

--精力发生变化
GuildExploreEvent.GUILDEXPLOREEVENT_ENERGYCHANGED = "GUILDEXPLOREEVENT_ENERGYCHANGED"
--点击灵泉获取属性
GuildExploreEvent.GUILDEXPLOREEVENT_HIPP_BUFF_CHANGE = "GUILDEXPLOREEVENT_HIPP_BUFF_CHANGE"


--事件变化
GuildExploreEvent.GUILDEXPLOREEVENT_EVENTCHANGE =  "GUILDEXPLOREEVENT_EVENTCHANGE"

--地图数据发生变化
GuildExploreEvent.GUILDEXPOREEVENT_MAPCHANGE =  "GUILDEXPOREEVENT_MAPCHANGE"
--地图数据删除
GuildExploreEvent.GUILDEXPOREEVENT_MAPDELETE =  "GUILDEXPOREEVENT_MAPDELETE"

--隐藏怪物的介绍界面
GuildExploreEvent.GUILDEXPOREEVENT_HIDDEN_MONSTERUI = "GUILDEXPOREEVENT_HIDDEN_MONSTERUI"

--派遣成功事件
GuildExploreEvent.GUILDEXPOREEVENT_DISPATCH_PANTNER = "GUILDEXPOREEVENT_DISPATCH_PANTNER"

--刷新装备界面的事件
GuildExploreEvent.GUILDEXPOREEVENT_REFREISH_EQUIPMENT_UI = "GUILDEXPOREEVENT_REFREISH_EQUIPMENT_UI"

--派遣刷新
GuildExploreEvent.GUILDEXPOREEVENT_SEND_PANTNER_UI = "GUILDEXPOREEVENT_SEND_PANTNER_UI"

--功能玩法战斗结束
-- GuildExploreEvent.GUILDEXPLORE_BATTLE_END = "GUILDEXPLORE_BATTLE_END"
--矿脉服务器协议报错的刷新回调事件
GuildExploreEvent.GUILDEXPLORE_MINE_SERVE_ERROR_REFRESHUI = "GUILDEXPLORE_MINE_SERVE_ERROR_REFRESHUI"
--建筑服务器协议报错的刷新回调事件
GuildExploreEvent.GUILDEXPLORE_CITY_SERVE_ERROR_REFRESHUI = "GUILDEXPLORE_CITY_SERVE_ERROR_REFRESHUI"
GuildExploreEvent.GUILDEXPLORE_CITY_SERVE_ERROR_POS_REFRESHUI = "GUILDEXPLORE_CITY_SERVE_ERROR_POS_REFRESHUI"

--关闭地图路线
GuildExploreEvent.GUILDEXPLORE_CLOSEMAPPATH = "GUILDEXPLORE_CLOSEMAPPATH"

--恢复地图缩放
GuildExploreEvent.GUILDEXPLORE_RESUMESCALE = "GUILDEXPLORE_RESUMESCALE"


--离线奖励刷新
GuildExploreEvent.GUILD_EXPLORE_OFF_LINE_REWARD = "GUILD_EXPLORE_OFF_LINE_REWARD"

--主城按钮是否显示
GuildExploreEvent.GUILD_EXPLORE_MAIN_ISSHOW = "GUILD_EXPLORE_MAIN_ISSHOW"

--刷新主城按钮红点
GuildExploreEvent.GUILD_EXPLORE_REFESH_RED = "GUILD_EXPLORE_REFESH_RED"


--当有buff 开启时
GuildExploreEvent.GUILD_EXPLORE_BUFFOPEN = "GUILD_EXPLORE_BUFFOPEN"

--主界面任务刷新
GuildExploreEvent.GUILD_EXPLORE_TASK_REFRESH  = "GUILD_EXPLORE_TASK_REFRESH"

--入口活动红点刷新
GuildExploreEvent.GUILDE_EXPLORE_ROKOU_RED_FRESISH = "GUILDE_EXPLORE_ROKOU_RED_FRESISH"



return GuildExploreEvent 