
local HappySignEvent = {}

HappySignEvent.RED_POINT_EVENT = "RED_POINT_EVENT";
HappySignEvent.FINISH_ALL_SIGN_EVENT = "FINISH_ALL_SIGN_EVENT";
HappySignEvent.ONLINED_DAYS_CHANGED_EVENT = "ONLINED_DAYS_CHANGED_EVENT";
--领取可选奖励
HappySignEvent.GET_HAPPYSIGN_OPTION_REWARD = "GET_HAPPYSIGN_OPTION_REWARD";
--领取可选奖励完成
HappySignEvent.HAPPYSIGN_OPTION_REWARD_CALLBACK = "HAPPYSIGN_OPTION_REWARD_CALLBACK"
return HappySignEvent


