--[[
	Author: lichaoye
	Date: 2017-04-13
	查看阵容-Event
]]
local LineUpEvent = {}

LineUpEvent.PRAISE_UPDATE_EVENT = "PRAISE_UPDATE_EVENT" -- 点赞情况刷新
LineUpEvent.PRAISE_LIST_UPDATE_EVENT = "PRAISE_LIST_UPDATE_EVENT" -- 赞我的人列表更新
LineUpEvent.PARTNER_FORMATION_UPDATE_EVENT = "PARTNER_FORMATION_UPDATE_EVENT" -- 阵容改变
LineUpEvent.TREASURE_FORMATION_UPDATE_EVENT = "TREASURE_FORMATION_UPDATE_EVENT" -- 阵容改变
LineUpEvent.MAIN_CHANGE_PREVIEW_EVENT = "MAIN_CHANGE_PREVIEW_EVENT" -- 主界面变预览状态
LineUpEvent.BG_UPDATE_EVENT = "BG_UPDATE_EVENT" -- 主界面更换背景事件

return LineUpEvent