--登录相关事件
local LoginEvent = {}

LoginEvent.SERVEREVENT_INIT_SUCCESS = "LoginEvent.SERVEREVENT_INIT_SUCCESS"
LoginEvent.SERVEREVENT_INIT_FAIL = "LoginEvent.SERVEREVENT_INIT_FAIL "

--登录成功
LoginEvent.LOGINEVENT_LOGIN_SUCCESS = "LOGINEVENT_LOGIN_SUCCESS"
-- 登录失败
LoginEvent.LOGINEVENT_LOGIN_FAIL = "LOGINEVENT_LOGIN_FAIL"

--获取区服列表成功
LoginEvent.LOGINEVENT_GET_SERVER_LIST_OK = "LOGINEVENT_GET_SERVER_LIST_OK"
--选区发生变化
LoginEvent.LOGINEVENT_CHANGEZONE = "LOGINEVENT_CHANGEZONE"
--选区失败
LoginEvent.LOGINEVENT_SELECT_ZONE_FAIL = "LoginEvent.LOGINEVENT_SELECT_ZONE_FAIL"
-- 选区成功
LoginEvent.LOGINEVENT_SELECT_ZONE_SUCCESS = "LoginEvent.LOGINEVENT_SELECT_ZONE_SUCCESS"

--获取服务器列表失败
LoginEvent.LOGINEVENT_GET_SERVER_LIST_FAIL = "LoginEvent.LOGINEVENT_GET_SERVER_LIST_FAIL"

LoginEvent.LOGINEVENT_REGIST_OK = "LOGINEVENT_REGIST_OK"

LoginEvent.LOGINEVENT_LOG_OUT = "LOGINEVENT_LOG_OUT"

--绑定账号成功
LoginEvent.LOGINEVENT_BIND_ACCOUNT_SUCCESS = "LOGINEVENT_BIND_ACCOUNT_SUCCESS"

--绑定账号失败
LoginEvent.LOGINEVENT_BIND_ACCOUNT_FAIL = "LOGINEVENT_BIND_ACCOUNT_FAIL"

--登录成功，更新model数据完成
LoginEvent.LOGINEVENT_LOGIN_UPDATE_MODEL_COMPLETE = "LOGINEVENT_LOGIN_UPDATE_MODEL_COMPLETE"


LoginEvent.LOGINEVENT_GUEST_BINDING_SUCCESS = "LOGINEVENT_GUEST_BINDING_SUCCESS"

LoginEvent.LOGINEVENT_SHOW_SELECT_WAY = "LOGINEVENT_SHOW_SELECT_WAY"

-- 同意协议
LoginEvent.LOGINEVENT_ON_AGREE = "LOGINEVENT_ON_AGREE"
-- 选角界面关闭
LoginEvent.LOGINEVENT_CLOSE_SELECT_ROLE_VIEW = "LoginEvent.LOGINEVENT_CLOSE_SELECT_ROLE_VIEW"
-- 检查开服时间
LoginEvent.LOGINEVENT_CHECK_SERVER_OPEN_TIME = "LoginEvent.LOGINEVENT_CHECK_SERVER_OPEN_TIME"

--重登回来
LoginEvent.LOGINEVENT_RELOGINBACK = "LOGINEVENT_RELOGINBACK"

-- 主城公告关闭
LoginEvent.LOGINEVENT_CLOSE_HOME_GONGGAO = "LoginEvent.LOGINEVENT_CLOSE_HOME_GONGGAO"

-- 排队时间结束
LoginEvent.LOGINEVENT_QUEUE_TIME_END = "LoginEvent.LOGINEVENT_QUEUE_TIME_END"

return LoginEvent
