-- 幸运转盘
local LuckyGuyEvent = {}

--抽完奖刷新主界面
LuckyGuyEvent.LUCKYGUY_PLAY_SUCCESS_EVENT = "LUCKYGUY_PLAY_SUCCESS_EVENT"
--抽完奖把奖励送给界面展示
LuckyGuyEvent.LUCKYGUY_PLAY_REWARD_EVENT = "LUCKYGUY_PLAY_REWARD_EVENT"
--刷新幸运值
LuckyGuyEvent.LUCKYGUY_REFRESH_LUCKNUMBER_EVENT = "LUCKYGUY_REFRESH_LUCKNUMBER_EVENT"
--在抽一次
LuckyGuyEvent.LUCKYGUY_PLAY_AGAIN_ONE_EVENT = "LUCKYGUY_PLAY_AGAIN_ONE_EVENT"
--再抽五次
LuckyGuyEvent.LUCKYGUY_PLAY_AGAIN_FIVE_EVENT = "LUCKYGUY_PLAY_AGAIN_FIVE_EVENT"

LuckyGuyEvent.LUCKYGUY_IS_OPEN_EVENT = "LUCKYGUY_IS_OPEN_EVENT"

--刷新主城转盘的红点   只有点击免费抽取才发动
LuckyGuyEvent.LUCKYGUY_REFRESH_MAIN_RED = "LUCKYGUY_REFRESH_MAIN_RED"

-- 刷新每次花费的txt
LuckyGuyEvent.LUCKYGUY_REFRESH_MONEY_TXT = "LUCKYGUY_REFRESH_MONEY_TXT"

return LuckyGuyEvent