local MissionEvent = {}

MissionEvent.MISSIONUI_REFRESH = "MISSIONUI_REFRESH"
MissionEvent.CHUZHANDOU_EVENT = "CHUZHANDOU_EVENT"
MissionEvent.BOX_REFRENSH = "MissionEvent.BOX_REFRENSH"
MissionEvent.MISSIONUI_OVER = "MISSIONUI_OVER"
MissionEvent.MISSIONUI_REFRESH_DATI_NUM = "MISSIONUI_REFRESH_DATI_NUM"

-- 关闭问答
MissionEvent.CLOSE_MISSION_QUEST_VIEW = "MissionEvent.CLOSE_MISSION_QUEST_VIEW"

return MissionEvent