-- 月卡
local MonthCardEvent = {}

MonthCardEvent.MONTH_CARD_BUY_SUCCESS_EVENT = "MONTH_CARD_BUY_SUCCESS_EVENT"

MonthCardEvent.MONTH_CARD_RECHARGE_SUCCESS_EVENT = "MONTH_CARD_RECHARGE_SUCCESS_EVENT"

MonthCardEvent.MONTH_CARD_TIME_OVER_EVENT = "MONTH_CARD_TIME_OVER_EVENT"

MonthCardEvent.MONTH_CARD_REFRESH_RED_POINT_EVENT = "MONTH_CARD_REFRESH_RED_POINT_EVENT"

return MonthCardEvent