--caocheng

local NewLoveEvent = {}

-- 一条情缘成功升阶
NewLoveEvent.NEWLOVEEVENT_ONE_LOVE_LEVEL_UP_GRADE = "NEWLOVEEVENT_ONE_LOVE_LEVEL_UP_GRADE"
-- 伙伴的共鸣阶升阶成功升阶刷新界面用
NewLoveEvent.NEWLOVEEVENT_ONE_PARTNER_RESONATE_ONE_STEP = "NEWLOVEEVENT_ONE_PARTNER_RESONATE_ONE_STEP"
-- 伙伴共鸣成功  播放动画用
NewLoveEvent.NEWLOVEEVENT_PLAY_ANIMAtion_EVENT = "NEWLOVEEVENT_PLAY_ANIMAtion_EVENT"
-- 激活或者提升 播完动画发出的事件
NewLoveEvent.NEWLOVEEVENT_ANIMATION_OVER_EVENT = "NEWLOVEEVENT_ANIMATION_OVER_EVENT"

-- 战斗胜利，提升情缘值
NewLoveEvent.NEWLOVEEVENT_BATTLE_WIN = "NEWLOVEEVENT_BATTLE_WIN"
-- 退出剧情
NewLoveEvent.NEWLOVEEVENT_PLOT_EXIT = "NEWLOVEEVENT_PLOT_EXIT"
-- 跳过剧情直接战斗 或者剧情结束 进入战斗
NewLoveEvent.NEWLOVEEVENT_PLOT_JUMP = "NEWLOVEEVENT_PLOT_JUMP"
NewLoveEvent.NEWLOVEEVENT_PLOT_FINISHED = "NEWLOVEEVENT_PLOT_FINISHED"
NewLoveEvent.NEWLOVEEVENT_UPDATE_RED = "NEWLOVEEVENT_UPDATE_RED"

-- 点亮一个单元,通知model做数据更新
NewLoveEvent.NEWLOVEEVENT_LIGHTEN_ONE_CELL = "NEWLOVEEVENT_LIGHTEN_ONE_CELL"
-- 底层model的全局属性更新 通知view做刷新
NewLoveEvent.NEWLOVEEVENT_UPDATE_GLOBAL_PROPERTY_DATA = "NEWLOVEEVENT_UPDATE_GLOBAL_PROPERTY_DATA"



return NewLoveEvent
