--//伙伴系统事件集合
--//2016-12-5 10:18:50
--//Author 狄建彬
local   PartnerEvent = PartnerEvent or {}

--某一个伙伴的信息发生了变化
PartnerEvent.PARTNER_INFO_CHANGE_EVENT = "PARTNER_INFO_CHANGE_EVENT"
--与伙伴系统相关的碎片发生了变化
PartnerEvent.PARTNER_FRAGMENT_CHANGE_EVENT = "PARTNER_FRAGMENT_CHANGE_EVENT"
--伙伴技能点发生了变化
PartnerEvent.PARTNER_SKILL_POINT_CHANGED = "PARTNER_SKILL_POINT_CHANGED"
--伙伴技能点的更新时间发生了变化
PartnerEvent.PARTNER_SKILL_POINT_UPDATE_TIME_CHANGED = "PARTNER_SKILL_POINT_UPDATE_TIME_CHANGED"
--伙伴的数目发生了变化
PartnerEvent.PARTNER_NUMBER_CHANGE_EVENT = "PARTNER_NUMBER_CHANGE_EVENT"
--某一个伙伴升级成功
PartnerEvent.PARTNER_LEVELUP_EVENT = "PARTNER_LEVELUP_EVENT"
--伙伴的星级提高
PartnerEvent.PARTNER_STAR_LEVELUP_EVENT = "PARTNER_STAR_LEVELUP_EVENT"
--星级节点发生变化
PartnerEvent.PARTNER_STAR_POINT_CHANGE_EVENT = "PARTNER_STAR_POINT_CHANGE_EVENT"
--伙伴的经验发生了变化
PartnerEvent.PARTNER_EXP_CHANGE_EVENT = "PARTNER_EXP_CHANGE_EVENT"
--伙伴品质装备位置发生变化
PartnerEvent.PARTNER_QUALITY_POSITION_CHANGE_EVENT = "PARTNER_QUALITY_POSITION_CHANGE_EVENT"
--伙伴品质装备等级发生变化
PartnerEvent.PARTNER_QUALITY_LEVEL_CHANGE_EVENT = "PARTNER_QUALITY_LEVEL_CHANGE_EVENT"
--品质发生变化
PartnerEvent.PARTNER_QUALITY_CHANGE_EVENT = "PARTNER_QUALITY_CHANGE_EVENT"
--伙伴品质道具合成
PartnerEvent.PARTNER_QUALITY_ITEM_COMBINE_EVENT = "PARTNER_QUALITY_ITEM_COMBINE_EVENT"
--伙伴的技能发生了变化
PartnerEvent.PARTNER_SKILL_CHANGED_EVENT = "PARTNER_SKILL_CHANGED_EVENT"
--伙伴的仙魂发生了变化
PartnerEvent.PARTNER_SOUL_CHANGE_EVENT = "PARTNER_SOUL_CHANGE_EVENT"
--顶部红点变化
PartnerEvent.PARTNER_TOP_REDPOINT_EVENT = "PARTNER_TOP_REDPOINT_EVENT"
--伙伴的装备强化
PartnerEvent.PARTNER_EQUIPMENT_ENHANCE_EVENT = "PARTNER_EQUIPMENT_ENHANCE_EVENT"
--装备觉醒
PartnerEvent.PARTNER_EQUIPMENT_AWAKE_EVENT = "PARTNER_EQUIPMENT_AWAKE_EVENT"
--伙伴消耗道具发生变化 红点显示
PartnerEvent.PARTNER_COST_ITEM_ENHANCE_EVENT = "PARTNER_COST_ITEM_ENHANCE_EVENT"
--伙伴UI 关闭消息
PartnerEvent.PARTNER_VIEW_CLOSE_EVENT = "PARTNER_VIEW_CLOSE_EVENT"
--伙伴 红点zong开关改变
PartnerEvent.PARTNER_REDPOINT_KAIGUAN_EVENT = "PARTNER_REDPOINT_KAIGUAN_EVENT"
--伙伴 红点开关改变
PartnerEvent.PARTNER_REDPOINT_ZONGKAIGUAN_EVENT = "PARTNER_REDPOINT_ZONGKAIGUAN_EVENT"
--伙伴 红点开关改变 影响 升品 升星 等UI内红点
PartnerEvent.PARTNER_REDPOINT_KAIGUAN_UI_EVENT = "PARTNER_REDPOINT_KAIGUAN_UI_EVENT"
--跳转到提升UI
PartnerEvent.PARTNER_CHANGE_TISHENG_UI_EVENT = "PARTNER_CHANGE_TISHENG_UI_EVENT"
--跳转到合成UI
PartnerEvent.PARTNER_CHANGE_HECHENG_UI_EVENT = "PARTNER_CHANGE_HECHENG_UI_EVENT"
--合成成功消息
PartnerEvent.PARTNER_HECHENG_SUCCESS_EVENT = "PARTNER_HECHENG_SUCCESS_EVENT"
--伙伴皮肤发生变化
PartnerEvent.PARTNER_SKIN_CHANGE_SUCCESS_EVENT = "PARTNER_SKIN_CHANGE_SUCCESS_EVENT"

PartnerEvent.PARTNER_PINGBI_UICLICK_EVENT = "PARTNER_PINGBI_UICLICK_EVENT"
PartnerEvent.PARTNER_HUIFU_UICLICK_EVENT = "PARTNER_HUIFU_UICLICK_EVENT"

PartnerEvent.PARTNER_ATTR_CHANGE_EVENT = "PARTNER_ATTR_CHANGE_EVENT"

-- 显示升级UI 消息
PartnerEvent.PARTNER_SHOW_UPGRADE_UI_EVENT = "PARTNER_SHOW_UPGRADE_UI_EVENT"
PartnerEvent.PARTNER_SHOW_UPGRADE_TYPE_EVENT = "PARTNER_SHOW_UPGRADE_TYPE_EVENT"
-- 隐藏升级UI 消息
PartnerEvent.PARTNER_HIDE_UPGRADE_UI_EVENT = "PARTNER_HIDE_UPGRADE_UI_EVENT"
PartnerEvent.PARTNER_START_HIDE_UPGRADE_UI_EVENT = "PARTNER_START_HIDE_UPGRADE_UI_EVENT"
-- 刷新升级UI 消息
PartnerEvent.PARTNER_UPDATE_UPGRADE_UI_EVENT = "PARTNER_UPDATE_UPGRADE_UI_EVENT"
-- 升级红点刷新
PartnerEvent.PARTNER_LEVEL_RED_EVENT = "PARTNER_LEVEL_RED_EVENT"
-- 立绘是否可滑动
PartnerEvent.PARTNER_LIHUI_MOVE_EVENT = "PARTNER_LIHUI_MOVE_EVENT"

-- 显示奇侠评论
PartnerEvent.PARTNER_SHOW_PINGLUN_UI_EVENT = "PARTNER_SHOW_PINGLUN_UI_EVENT"

PartnerEvent.PARTNER_CHANGEQINGBAO_EVENT = "PARTNER_CHANGEQINGBAO_EVENT"
--奇侠升级事件
PartnerEvent.PARTNER_UPGRADE_EVENT = "PartnerEvent.PARTNER_UPGRADE_EVENT"
--属性提升事件 需要播放飘字动画
PartnerEvent.PARTNER_ATTR_ANIM_EVENT = "PartnerEvent.PARTNER_ATTR_ANIM_EVENT"
--点击了仙术界面 修炼
PartnerEvent.PARTNER_SKILL_UP_EVENT = "PartnerEvent.PARTNER_SKILL_UP_EVENT"
--升级时 奇侠头像处需要播放爆点特效
PartnerEvent.PARTNER_LEVEL_ANIM_EVENT = "PartnerEvent.PARTNER_LEVEL_ANIM_EVENT"
--升星时 奇侠头像处需要播放爆点特效
PartnerEvent.PARTNER_STAR_ANIM_EVENT = "PartnerEvent.PARTNER_STAR_ANIM_EVENT"
--升品时需要 奇侠头像处需要播放爆点特效
PartnerEvent.PARTNER_QUALITY_ANIM_EVENT = "PartnerEvent.PARTNER_QUALITY_ANIM_EVENT"
--装备觉醒后需要播放战力特效
PartnerEvent.PARTNER_EQUIPMENT_AWAKE__BACK_EVENT = "PartnerEvent.PARTNER_EQUIPMENT_AWAKE__BACK_EVENT"
return PartnerEvent
