--家园系统相关事件
local QuestEvent = {}

QuestEvent.DAILY_QUEST_CHANGE_EVENT = "DAILY_QUEST_CHANGE_EVENT";
QuestEvent.MAINLINE_QUEST_CHANGE_EVENT = "MAINLINE_QUEST_CHANGE_EVENT";
QuestEvent.QUEST_CHECK_SP_EVENT = "QUEST_CHECK_SP_EVENT";
QuestEvent.AFTER_QUEST_GET_REWARD = "AFTER_QUEST_GET_REWARD";

QuestEvent.ACHIEVEMENT_GET_REWARD = "ACHIEVEMENT_GET_REWARD";
QuestEvent.UPGRADE_GET_REWARD = "UPGRADE_GET_REWARD";

QuestEvent.JUMP_FROM_QUEST = "JUMP_FROM_QUEST";

QuestEvent.CLOSE_UI_TRACK = "CLOSE_UI_TRACK";

QuestEvent.TOP_COMP_HOME_BUTTON = "TOP_COMP_HOME_BUTTON";

return QuestEvent


