local SettingEvent = {}

SettingEvent.SETTINGEVENT_MUSIC_SETTING_CHANGE = "SETTINGEVENT_MUSIC_SETTING_CHANGE"
SettingEvent.SETTINGEVENT_SOUND_SETTING_CHANGE = "SETTINGEVENT_SOUND_SETTING_CHANGE"
SettingEvent.SETTINGEVENT_SHOWPLSYER_SETTING_CHANGE = "SETTINGEVENT_SHOWPLSYER_SETTING_CHANGE"
SettingEvent.SETTINGEVENT_TEAMINVITE_SETTING_CHANGE = "SETTINGEVENT_TEAMINVITE_SETTING_CHANGE"

-- 通知设置变化
SettingEvent.SETTINGEVENT_PUSH_SETTING_CHANGE = "SETTINGEVENT_PUSH_SETTING_CHANGE"

return SettingEvent
