--
-- Author: xd
-- Date: 2016-01-18 15:14:12
--
local ShopEvent = {}
ShopEvent.SHOPEVENT_MODEL_UPDATE = "SHOPEVENT_MODEL_UPDATE"
ShopEvent.SHOPEVENT_BUY_ITEM_END = "SHOPEVENT_BUY_ITEM_END"
ShopEvent.SHOPEVENT_REFRESH_SHOP_END = "SHOPEVENT_REFRESH_SHOP_END"
ShopEvent.SHOPEVENT_GET_SHOP_END = "SHOPEVENT_GET_SHOP_END"
ShopEvent.SHOPEVENT_SHOP_JIEFENG_END = "SHOPEVENT_SHOP_JIEFENG_END"
ShopEvent.SHOPEVENT_SHOP_JIEFENG_VIEW_CLOSE = "SHOPEVENT_SHOP_JIEFENG_VIEW_CLOSE"
ShopEvent.SHOPEVENT_TEMP_SHOP_OPEN = "SHOPEVENT_TEMP_SHOP_OPEN"

ShopEvent.SHOPEVENT_NORAND_SHOP_REFRESHED = "SHOPEVENT_NORAND_SHOP_REFRESHED"

ShopEvent.SHOPEVENT_SYS_OPEN = "ShopEvent.SHOPEVENT_SYS_OPEN"

ShopEvent.SHOPEVENT_CHECK_SHOP_DATA = "SHOPEVENT_CHECK_SHOP_DATA"

ShopEvent.SHOP_REFRESH_BTNS = "SHOP_REFRESH_BTNS"

ShopEvent.OPEN_ANIM_END = "OPEN_ANIM_END"

ShopEvent.NORANDSHOPEVENT_MODEL_UPDATE = "NORANDSHOPEVENT_MODEL_UPDATE"
--关闭了商店的刷新界面
ShopEvent.SHOP_REFRESH_VIEW_CLOSED = "ShopEvent.SHOP_REFRESH_VIEW_CLOSED"
return ShopEvent
