--其他系统相关事件 比如时间更新, 比如 apk更新通知等
local SystemEvent = {}

SystemEvent.SYSTEMEVENT_APP_ENTER_BACKGROUND = "SYSTEMEVENT_APP_ENTER_BACKGROUND"  		--失去游戏焦点  参数  {time ,usec }
SystemEvent.SYSTEMEVENT_APP_ENTER_FOREGROUND = "SYSTEMEVENT_APP_ENTER_FOREGROUND" 		--恢复游戏焦点  参数  {time ,usec ,dt} )
SystemEvent.SYSTEMEVENT_APP_WILL_TERMINATE = "SYSTEMEVENT_APP_WILL_TERMINATE" 			--游戏将被杀死
	
SystemEvent.SYSTEMEVENT_LOGS_NORMAL = "SYSTEMEVENT_LOGS_NORMAL"
SystemEvent.SYSTEMEVENT_LOGS_ERROR = "SYSTEMEVENT_LOGS_ERROR"

-- CompServerOverTimeTipView界面关闭消息
SystemEvent.SYSTEMEVENT_COMP_SERVEROVER_CLOSE = "SystemEvent.SYSTEMEVENT_COMP_SERVEROVER_CLOSE"

--c端收到一个加载纹理的消息
SystemEvent.SYSTEMEVENT_LOAD_TEXTURE_PATH = "SYSTEMEVENT_LOAD_TEXTURE_PATH"

-- android下后台切回前台重新绘制纹理
SystemEvent.SYSTEMEVENT_RENTER_RE_CREATE = "SYSTEMEVENT_RENTER_RE_CREATE"


SystemEvent.SYSTEMEVENT_ONSERVERERROR = "SYSTEMEVENT_ONSERVERERROR"

return SystemEvent