--
-- Author: xd
-- Date: 2015-12-08 20:26:43

--

local TimeEvent = {}

TimeEvent.TIMEEVENT_ONSP = "TIMEEVENT_ONSP"  				--体力恢复间隔到了

TimeEvent.TIMEEVENT_CDSHOP_1 = "TIMEEVENT_CDSHOP_1" 		--商城1的刷新时间
TimeEvent.TIMEEVENT_CDSHOP_2 = "TIMEEVENT_CDSHOP_2" 		--商城2的刷新时间
TimeEvent.TIMEEVENT_CDSHOP_3 = "TIMEEVENT_CDSHOP_3" 		--商城3的刷新时间
TimeEvent.TIMEEVENT_CDSHOP_9 = "TIMEEVENT_CDSHOP_9" 		--商城3的刷新时间
TimeEvent.TIMEEVENT_CDSHOP_4 = "TIMEEVENT_CDSHOP_4" 		--熔炼灵宝阁刷新时间
TimeEvent.TIMEEVENT_CDSHOP_6 = "TIMEEVENT_CDSHOP_6"
TimeEvent.TIMEEVENT_CDSHOP_10 = "TIMEEVENT_CDSHOP_10"
TimeEvent.TIMEEVENT_CDSHOP_14 = "TIMEEVENT_CDSHOP_14"

TimeEvent.TIMEEVENT_TOKEN_LOTTERY_CD = "TIMEEVENT_TOKEN_LOTTERY_CD" 	--抽卡系统，令牌抽卡cd
TimeEvent.TIMEEVENT_GOLD_LOTTERY_CD = "TIMEEVENT_GOLD_LOTTERY_CD" 		--抽卡系统，钻石抽卡cd

TimeEvent.TIMEEVENT_PVP_SHOP_REFRESH_CD = "TIMEEVENT_PVP_SHOP_REFRESH_CD"
TimeEvent.TIMEEVENT_PVP_FAST_REFRESH_CD = "TIMEEVENT_PVP_FAST_REFRESH_CD"

TimeEvent.TIMEEVENT_CHAR_SHOP_REFRESH_CD = "TIMEEVENT_CHAR_SHOP_REFRESH_CD"
--到达了某个固定时间
TimeEvent.TIMEEVENT_STATIC_CLOCK_REACH_EVENT = "TIMEEVENT_STATIC_CLOCK_REACH_EVENT"

--伙伴系统,技能点回复时间
TimeEvent.TIMEEVENT_PARTNER_SKILL_POINT_RESUME_EVENT = "TIMEEVENT_PARTNER_SKILL_POINT_RESUME_EVENT"
-- 七登签到结束凌晨4点刷新入口事件
TimeEvent.TIMEEVENT_HAPPYSIGN_END_EVENT = "TIMEEVENT_HAPPYSIGN_END_EVENT"
-- 仙盟商店刷新时间
TimeEvent.TIMEEVENT_GUILD_SHOP_REFRESH_CD = "TIMEEVENT_GUILD_SHOP_REFRESH_CD"
-- 锁妖塔商店刷新
TimeEvent.TIMEEVENT_TOWER_SHOP_REFRESH_CD = "TIMEEVENT_TOWER_SHOP_REFRESH_CD"
-- 须臾商店刷新
TimeEvent.TIMEEVENT_WONDER_SHOP_REFRESH_CD = "TIMEEVENT_WONDER_SHOP_REFRESH_CD"
--永安当刷新
TimeEvent.TIMEEVENT_MALL_YONGANDANG_REFRESH_CD = "TIMEEVENT_MALL_YONGANDANG_REFRESH_CD"

--跨天了
TimeEvent.TIMEEVENT_HAS_OVER_DAY = "TIMEEVENT_HAS_OVER_DAY"
return TimeEvent
