--锁妖塔系统相关事件

local TowerEvent = {}

-- 地图相关事件

-- 主角移动到了目标格子
TowerEvent.TOWEREVENT_CHAR_ARRIVE_TARGET_GIRD = "TowerEvent.TOWEREVENT_CHAR_ARRIVE_TARGET_GIRD"

-- 当主角运动到一个格子
TowerEvent.TOWEREVENT_CHAR_ARRIVE_GIRD = "TowerEvent.TOWEREVENT_CHAR_ARRIVE_GIRD"

-- 选择目标
TowerEvent.TOWEREVENT_CHOOSE_TARGET = "TowerEvent.TOWEREVENT_CHOOSE_TARGET"

-- -- 打开格子成功消息
-- TowerEvent.TOWEREVENT_OPEN_GRID_SUCCESS = "TowerEvent.TOWEREVENT_OPEN_GRID_SUCCESS"

-- 点击了一个格子
TowerEvent.TOWEREVENT_CLICK_GRID = "TowerEvent.TOWEREVENT_CLICK_GRID"

-- 锁妖塔数据更新完毕
TowerEvent.TOWEREVENT_TOWER_DATA_UPDATE = "TowerEvent.TOWEREVENT_TOWER_DATA_UPDATE"

-- 杀怪成功
TowerEvent.TOWEREVENT_ATTACK_MONSTER_SUCCESS = "TowerEvent.TOWEREVENT_ATTACK_MONSTER_SUCCESS"

-- 杀怪失败
TowerEvent.TOWEREVENT_ATTACK_MONSTER_FAIL = "TowerEvent.TOWEREVENT_ATTACK_MONSTER_FAIL"

-- 怪死亡消息
TowerEvent.TOWEREVENT_MONSTER_DIE = "TowerEvent.TOWEREVENT_MONSTER_DIE"

-- 开宝箱成功
TowerEvent.TOWEREVENT_OPEN_BOX_SUCCESS = "TowerEvent.TOWEREVENT_OPEN_BOX_SUCCESS"

-- 战斗成功
TowerEvent.TOWEREVENT_BATTLE_SUCCESS = "TowerEvent.TOWEREVENT_BATTLE_SUCCESS"

-- 战斗失败
TowerEvent.TOWEREVENT_BATTLE_FAIL = "TowerEvent.TOWEREVENT_BATTLE_FAIL"

-- 地图内商店开启
TowerEvent.TOWEREVENT_MAP_SHOP_OPEN = "TowerEvent.TOWEREVENT_MAP_SHOP_OPEN"

-- 地图内商店消失(过期或购买完毕)
TowerEvent.TOWEREVENT_MAP_SHOP_CLOSE = "TowerEvent.TOWEREVENT_MAP_SHOP_CLOSE"

-- 地图商店buff界面关闭
TowerEvent.TOWEREVENT_BUFF_SHOP_VIEW_CLOSE = "TowerEvent.TOWEREVENT_BUFF_SHOP_VIEW_CLOSE"

--更新界面内的时间
TowerEvent.TOWEREVENT_UPDATA_SHOP_TIME = "TowerEvent.TOWEREVENT_UPDATA_SHOP_TIME"

--进入战斗
TowerEvent.TOWEREVENT_ENTER_BATTLE = "TowerEvent.TOWEREVENT_ENTER_BATTLE"

--假战斗
TowerEvent.TOWEREVENT_ENTER_BATTLE_KK ="TowerEvent.TOWEREVENT_ENTER_BATTLE_KK"

-- 捡道具成功
TowerEvent.TOWEREVENT_GET_ITEM_SUCCESS = "TowerEvent.TOWEREVENT_GET_ITEM_SUCCESS"

-- 道具展示界面点击了确认使用道具，收到该消息后展示相关动画
TowerEvent.TOWEREVENT_CLICK_USE_ITEM = "TowerEvent.TOWEREVENT_CLICK_USE_ITEM"

-- 开始使用道具
TowerEvent.TOWEREVENT_BEGIN_USE_ITEM = "TowerEvent.TOWEREVENT_BEGIN_USE_ITEM"

-- 使用道具成功(道具model监听该消息进行逻辑处理)
TowerEvent.TOWEREVENT_USE_ITEM_SUCCESS = "TowerEvent.TOWEREVENT_USE_ITEM_SUCCESS"

-- 使用道具失败
TowerEvent.TOWEREVENT_USE_ITEM_FAIL = "TowerEvent.TOWEREVENT_USE_ITEM_FAIL"

-- 更新道具(界面道具更新使用该消息，不使用TowerEvent.TOWEREVENT_USE_ITEM_SUCCESS)
TowerEvent.TOWEREVENT_USE_ITEM_UPDATE = "TowerEvent.TOWEREVENT_USE_ITEM_UPDATE"

-- 丢失道具成功
TowerEvent.TOWEREVENT_DROP_ITEM_SUCCESS = "TowerEvent.TOWEREVENT_DROP_ITEM_SUCCESS"

-- 绕过怪
TowerEvent.TOWEREVENT_SKIP_MONSTER = "TowerEvent.TOWEREVENT_SKIP_MONSTER"

--主界面重置
TowerEvent.TOWEREVENT_RESET_TOWER = "TowerEvent.TOWEREVENT_RESET_TOWER"

--主界面扫荡
TowerEvent.TOWEREVENT_SWEEP_TOWER = "TowerEvent.TOWEREVENT_SWEEP_TOWER"
TowerEvent.TOWEREVENT_COLLECT_TOWER = "TowerEvent.TOWEREVENT_COLLECT_TOWER"

--重置锁妖塔成功
TowerEvent.TOWEREVENT_RESET_TOWER_SUCCESS = "TowerEvent.TOWEREVENT_RESET_TOWER_SUCCESS"

--购买单体buff成功
TowerEvent.TOWEREVENT_BUYBUFF_TOWER_SUCCESS = "TowerEvent.TOWEREVENT_BUYBUFF_TOWER_SUCCESS"

-- 关闭锁妖塔奖励界面
TowerEvent.TOWEREVENT_CLOSE_GETREWARDVIEW = "TowerEvent.TOWEREVENT_CLOSE_GETREWARDVIEW"

--领取登塔奖励
TowerEvent.TOWEREVENT_SUCCESS_GETMAINREWARDVIEW = "TowerEvent.TOWEREVENT_SUCCESS_GETMAINREWARDVIEW"

--更新重置状态
TowerEvent.TOWEREVENT_UPDATE_TESETTOWERTYPE = "TowerEvent.TOWEREVENT_UPDATE_TESETTOWERTYPE"

--破阵上阵伙伴
TowerEvent.TOWEREVENT_GOINTO_MATRIXMETHOD =  "TowerEvent.TOWEREVENT_GOINTO_MATRIXMETHOD"

--选择进入锁妖塔
TowerEvent.TOWEREVENT_ENTER_TOWERMAPVIEW = "TowerEvent.TOWEREVENT_ENTER_TOWERMAPVIEW"

--锁妖塔拼图事件
TowerEvent.TOWEREVENT_MINIGAME_TIME_OUT =  "TowerEvent.TOWEREVENT_MINIGAME_TIME_OUT"

--锁妖塔拾取道具
TowerEvent.TOWEREVENT_CHOOSE_GET_ITEM = "TowerEvent.TOWEREVENT_CHOOSE_GET_ITEM"

--自动打开剩余所有格子
TowerEvent.TOWEREVENT_AUTO_OPEN_LEFT_GRIDS = "TowerEvent.TOWEREVENT_AUTO_OPEN_LEFT_GRIDS"

--本次购买的buff
TowerEvent.TOWEREVENT_BUYBUFF_TOWERMAP_SUCCESS = "TowerEvent.TOWEREVENT_BUYBUFF_TOWERMAP_SUCCESS"

--进入下一层
TowerEvent.TOWEREVENT_ENTER_NEXTFLOOR = "TowerEvent.TOWEREVENT_ENTER_NEXTFLOOR"

--进入下一层完成
TowerEvent.TOWEREVENT_ENTER_NEXTFLOOR_COMPLETE = "TOWEREVENT_ENTER_NEXTFLOOR_COMPLETE"

-- 更新战斗后结果数据
TowerEvent.TOWEREVENT_UPDATE_BATTLE_DATA = "TowerEvent.TOWEREVENT_UPDATE_BATTLE_DATA"

-- 更新战斗后结果数据成功
TowerEvent.TOWEREVENT_UPDATE_BATTLE_DATA_SUCCESS = "TowerEvent.TOWEREVENT_UPDATE_BATTLE_DATA_SUCCESS"

-- 破阵
TowerEvent.TOWEREVENT_TAKEALTAR = "TowerEvent.TOWEREVENT_TAKEALTAR"

-- 刷新地图格子
TowerEvent.TOWEREVENT_UPDATE_GRIDS = "TowerEvent.TOWEREVENT_UPDATE_GRIDS"
--翻格子动画
TowerEvent.TOWEREVENT_OVERTHEGRIDANIMATION = "TowerEvent.TOWEREVENT_OVERTHEGRIDANIMATION"

--笼子内的动画
TowerEvent.TOWEREVENT_UPDATATOWERITEMCAGE = "TowerEvent.TOWEREVENT_UPDATATOWERITEMCAGE"

--笼子内动画播放
TowerEvent.TOWEREVENT_CLOSETOWERITEMCAGE = "TowerEvent.TOWEREVENT_CLOSETOWERITEMCAGE"

--关闭锁妖塔奖励界面时有塔类道具 
TowerEvent.TOWEREVENT_HAVE_TOWERITEM = "TowerEvent.TOWEREVENT_HAVE_TOWERITEM"

-- 确认收取五灵
TowerEvent.TOWEREVENT_GOT_SOUL_COMFIRMED = "TowerEvent.TOWEREVENT_GOT_SOUL_COMFIRMED"
-- 确认关闭商店
TowerEvent.TOWEREVENT_CLOSE_MAP_SHOP_CONFIRMED = "TowerEvent.TOWEREVENT_CLOSE_MAP_SHOP_CONFIRMED"
-- 底层数据刷新后 发送消息告诉劫财劫色界面刷新随机伙伴
-- (劫色时在界面恢复时没法正确判断伙伴是否死亡,需等待底层数据刷新后再次刷新)
TowerEvent.TOWEREVENT_REFRESH_RANDOM_FEMALE_PARTNER = "TowerEvent.TOWEREVENT_REFRESH_RANDOM_FEMALE_PARTNER"
-- 检查是否完美通关(紫金葫芦杀怪成功 发送此消息)
TowerEvent.TOWEREVENT_CHECK_IS_PERFECT = "TowerEvent.TOWEREVENT_CHECK_IS_PERFECT"



--道具杀怪(非战斗杀怪，使用道具直接杀怪) 
TowerEvent.TOWEREVENT_ITEM_KILL_MONSTER = "TowerEvent.TOWEREVENT_ITEM_KILL_MONSTER"
-- 场景中是否有警戒怪 发生变化(有变无 无变有)
TowerEvent.TOWER_IS_HAS_ALERT_MONSTER_CHANGE = "TOWER_IS_HAS_ALERT_MONSTER_CHANGE"

-- 变更生效的符文成功
TowerEvent.TOWER_CHANGE_RUNE_SUCCEED = "TOWER_CHANGE_RUNE_SUCCEED"


-- 搜刮出一个奖励 或者事件
TowerEvent.TOWER_COLLECT_FIND_ONE_RESULT = "TOWER_COLLECT_FIND_ONE_RESULT"
-- 确认前往处理搜刮事件
TowerEvent.TOWER_GO_TO_HANDLE_EVENTS_CONFIRMED = "TOWER_GO_TO_HANDLE_EVENTS_CONFIRMED"
TowerEvent.TOWER_GO_TO_ACCELERATE_COLLECTION_CONFIRMED = "TOWER_GO_TO_ACCELERATE_COLLECTION_CONFIRMED"
TowerEvent.TOWER_GO_TO_BUY_GOODS_CONFIRMED = "TOWER_GO_TO_BUY_GOODS_CONFIRMED"
TowerEvent.TOWER_GO_TO_RE_DIVINATION_CONFIRMED = "TOWER_GO_TO_RE_DIVINATION_CONFIRMED" 
-- 一个事件处理完毕
TowerEvent.TOWER_HANDLE_ONE_EVENT_SUCCEED = "TOWER_HANDLE_ONE_EVENT_SUCCEED"

-- 搜刮加速 数据更新完成
TowerEvent.TOWEREVENT_TOWER_ACCELERATE_DATA_UPDATE_SUCCEED = "TOWEREVENT_TOWER_ACCELERATE_DATA_UPDATE_SUCCEED"


-- 搜刮红点发生变化
TowerEvent.TOWEREVENT_TOWER_COLLECTION_REDPOINT_CHANGED = "TOWEREVENT_TOWER_COLLECTION_REDPOINT_CHANGED"

-- 
TowerEvent.TOWEREVENT_CONFIRM_TO_CLICK_LOCK = "TOWEREVENT_CONFIRM_TO_CLICK_LOCK"
-- 换阶段时 确定进入下一层
TowerEvent.TOWEREVENT_CONFIRM_TO_ENTER_NEXT_FLOOR = "TOWEREVENT_CONFIRM_TO_ENTER_NEXT_FLOOR"
-- 已经检视过解锁商品
TowerEvent.TOWEREVENT_HAS_CHECK_UNLOCK_GOODS = "TOWEREVENT_HAS_CHECK_UNLOCK_GOODS"






return TowerEvent
