
--
--法宝相关事件
local TreasureNewEvent = {}

TreasureNewEvent.UP_QUALITY_SUCCESS_EVENT = "UP_QUALITY_SUCCESS_EVENT"
TreasureNewEvent.UP_STAR_SUCCESS_EVENT = "UP_STAR_SUCCESS_EVENT"
TreasureNewEvent.JUEXING_SUCCESS_EVENT = "JUEXING_SUCCESS_EVENT"
TreasureNewEvent.COMBINE_SUCCESS_EVENT = "COMBINE_TREASURE_SUCCESS_EVENT"
TreasureNewEvent.TREASURE_CHANGED_EVENT = "TREASURE_CHANGED_EVENT"
TreasureNewEvent.DRESS_TREASURE_SUCCESS = "TreasureNewEvent.DRESS_TREASURE_SUCCESS"

return TreasureNewEvent


