
local TrialEvent = {}

TrialEvent.BATTLE_SUCCESSS_EVENT = "BATTLE_SUCCESSS_EVENT";
TrialEvent.CLOSE_SWEEP_EVENT = "CLOSE_SWEEP_EVENT";
TrialEvent.SWEEP_BATTLE_SUCCESS_EVENT = "SWEEP_BATTLE_SUCCESS_EVENT";
TrialEvent.REFRESH_UI = "REFRESH_UI";
TrialEvent.AGAIN_MATCHING = "AGAIN_MATCHING" --重新匹配
TrialEvent.CLOSE_BLACK_EVENT = "CLOSE_BLACK_EVENT" ---匹配界面删除回调

return TrialEvent


