--用户系统相关事件
local UserEvent = {}

--更新了UserModel的数据
UserEvent.USEREVENT_MODEL_UPDATE = "USEREVENT_MODEL_UPDATE"

--删除model数据
UserEvent.USEREVENT_MODEL_DELETE = "USEREVENT_MODEL_DELETE"

-- 钻石变更消息
UserEvent.USEREVENT_GOLD_CHANGE = "USEREVENT_GOLD_CHANGE"
-- 体力变更消息
UserEvent.USEREVENT_SP_CHANGE = "USEREVENT_SP_CHANGE"
-- 等级变更消息
UserEvent.USEREVENT_LEVEL_CHANGE = "USEREVENT_LEVEL_CHANGE"
--//经验发生变化
UserEvent.USEREVENT_EXP_CHANGE = "USEREVENT_EXP_CHANGE"
--vip发生改变
UserEvent.USEREVENT_VIP_CHANGE = "USEREVENT_VIP_CHANGE"

--Coin发生变化
UserEvent.USEREVENT_COIN_CHANGE="USEREVENT_COIN_CHANGE"
-- 魔石发生变化
UserEvent.USEREVENT_DIMENSITY_CHANGE="USEREVENT_DIMENSITY_CHANGE"
--五灵币发生变化
UserEvent.USEREVENT_FIVESOULCOIN_CHANGE = "USEREVENT_FIVESOULCOIN_CHANGE"
--五灵点发生变化
UserEvent.USEREVENT_FIVESOULPOINT_CHANGE = "USEREVENT_FIVESOULPOINT_CHANGE"
--竞技场货币发生变化
UserEvent.USEREVENT_PVP_COIN_CHANGE = "USEREVENT_PVP_COIN_CHANGE"
-- 主角天赋点发生变化
UserEvent.USEREVENT_TALENT_POINT_CHANGE = "USEREVENT_TALENT_POINT_CHANGE"
-- 主角成就点发生变化
UserEvent.USEREVENT_ACHIEVMENT_POINT_CHANGE = "USEREVENT_ACHIEVMENT_POINT_CHANGE"
-- 委托币发生变化
UserEvent.USEREVENT_DEPUTE_POINT_CHANGE = "USEREVENT_DEPUTE_POINT_CHANGE"


UserEvent.USEREVENT_GARMENT_CHANGE = "USEREVENT_GARMENT_CHANGE"

-- 伙伴皮肤点券发生变化
UserEvent.USEREVENT_PARTNER_SKINCOIN_CHANGE = "USEREVENT_PARTNER_SKINCOIN_CHANGE"

--仙符数据变化
UserEvent.USEREVENT_XIANFU_CHANGE = "USEREVENT_XIANFU_CHANGE"

--战力发生变化
UserEvent.USEREVENT_PLAYER_POWER_CHANGE = "USEREVENT_PLAYER_POWER_CHANGE"

--法宝相关
UserEvent.USEREVENT_Treasure_LIST_CHANGE = "USEREVENT_Treasure_LIST_CHANGE"

--主角品阶发生了变化
UserEvent.USEREVENT_QUALITY_CHANGE = "USEREVENT_QUALITY_CHANGE"
--主角品阶装备位发生变化
UserEvent.USEREVENT_QUALITY_POSITION_CHANGE = "USEREVENT_QUALITY_POSITION_CHANGE"
--主角星级发生变化
UserEvent.USEREVENT_STAR_CHANGE = "USEREVENT_STAR_CHANGE"
--主角星级装备位发生变化
UserEvent.USEREVENT_STAR_POINT_CHANGE = "USEREVENT_STAR_POINT_CHANGE"
--主角装备发生变化
UserEvent.USEREVENT_EQUIPS_CHANGE = "USEREVENT_EQUIPS_CHANGE"

--主界面相关
UserEvent.HOME_MAGIC_NPC_EVENT = "HOME_MAGIC_NPC_EVENT"
UserEvent.HOME_NORMAL_NPC_TRIG_EVENT = "HOME_NORMAL_NPC_TRIG_EVENT"
UserEvent.HOME_NORMAL_NPC_UPDATE_EVENT = "HOME_NORMAL_NPC_UPDATE_EVENT"

UserEvent.USEREVENT_SET_AVATAR_OK = "USEREVENT_SET_AVATAR_OK"

UserEvent.USEREVENT_NAME_CHANGE_OK = "USEREVENT_NAME_CHANGE_OK"
UserEvent.USEREVENT_SET_NAME_OK= "USEREVENT_SET_NAME_OK"

-- 精英副本战斗次数发生变化
UserEvent.USEREVENT_STAGE_COUNTS_CHANGE = "USEREVENT_STAGE_COUNTS_CHANGE"

UserEvent.USEREVENT_CLOSE_LVL_UP_VIEW = "USEREVENT_CLOSE_LVL_UP_VIEW"

-- 关闭设置昵称界面
UserEvent.USEREVENT_CLOSE_SET_NICK_NAME_VIEW = "USEREVENT_CLOSE_SET_NICK_NAME_VIEW"

--登陆游戏
UserEvent.LOGIN_ENTER_GAME_RES_LOADING = "LOGIN_ENTER_GAME_RES_LOADING"

--换头像
UserEvent.USER_CHANGE_HEAD_EVENT = "USER_CHANGE_HEAD_EVENT"
--换头像框
UserEvent.USER_CHANGE_HEAD_FRAM_EVENT = "USER_CHANGE_HEAD_FRAM_EVENT"
 
--更换签名
UserEvent.USER_CHANGE_QIAN_MING_EVENT = "USER_CHANGE_QIAN_MING_EVENT"

--主角信息发生变化
UserEvent.USER_INFO_CHANGE_EVENT = "USER_INFO_CHANGE_EVENT"

--灵石变化
UserEvent.USEREVENT_CHANGE_SPIRITSTONES = "UserEvent.USEREVENT_CHANGE_SPIRITSTONES"

--反馈成功
UserEvent.USEREVENT_FEEDBACK_SUCCESS = "USEREVENT_FEEDBACK_SUCCESS"

UserEvent.USEREVENT_GUILDCOIN_SUCCESS = "USEREVENT_GUILDCOIN_SUCCESS"

UserEvent.USEREVENT_WONDERLAND_DATA = "USEREVENT_WONDERLAND_DATA"
-- 购买体力成功
UserEvent.USEREVENT_BUY_SP_SUCCESS = "USEREVENT_BUY_SP_SUCCESS"
--主城按钮刷新事件
UserEvent.BUTTON_REFRESH_EVENT = "BUTTON_REFRESH_EVENT"
-- 巅峰竞技场货币变化
UserEvent.USEREVENT_CROSSPEAKCOIN_CHANGE = "USEREVENT_CROSSPEAKCOIN_CHANGE"

-- 特权发生变化
UserEvent.USEREVENT_TEQUAN_CHANGE = "USEREVENT_TEQUAN_CHANGE"

--转盘抽奖券发生变化
UserEvent.USEREVENT_ROULETTE_COIN_CHANGE="USEREVENT_ROULETTE_COIN_CHANGE"


return UserEvent







