--版本管理事件
local VersionEvent = {}

--检查服务器地址
VersionEvent.VERSIONEVENT_CHECK_GLOBAL_SERVER = "VERSIONEVENT_CHECK_GLOBAL_SERVER"

--检查版本
VersionEvent.VERSIONEVENT_CHECK_VERSION = "VERSIONEVENT_CHECK_VERSION"

--下载更新包
VersionEvent.VERSIONEVENT_UPDATE_PACKAGE = "VERSIONEVENT_UPDATE_PACKAGE"

--确定下载更新包
VersionEvent.VERSIONEVENT_UPDATE_STAR = "VersionEvent.VERSIONEVENT_UPDATE_STAR"

return VersionEvent