--六界系统相关事件
local WorldEvent = {}

--播放六界的背景音乐
WorldEvent.WORLDEVENT_PLAY_BGMUSIC = "WORLDEVENT_PLAY_BGMUSIC"
--节点成绩发生变化
WorldEvent.WORLDEVENT_CHAPTER_STAGE_SCORE_UPDATE = "WORLDEVENT_CHAPTER_STAGE_SCORE_UPDATE"

--节点成绩从非三星修变化为三星
WorldEvent.WORLDEVENT_CHAPTER_STAGE_SCORE_DELETE = "WORLDEVENT_CHAPTER_STAGE_SCORE_DELETE"

-- 额外奖励界面关闭
WorldEvent.WORLDEVENT_EXTREA_REWARD_VIEW_CLOSE = "WORLDEVENT_EXTREA_REWARD_VIEW_CLOSE"

-- 开启奇缘窗口关闭
WorldEvent.WORLDEVENT_UNLOCK_ROMANCE_CLOSE = "WORLDEVENT_UNLOCK_ROMANCE_CLOSE"

-- 关闭PVE 战斗界面
WorldEvent.WORLDEVENT_CLOSE_PVE_BATTLE = "WORLDEVENT_CLOSE_PVE_BATTLE"

-- 关闭GVE 战斗界面
WorldEvent.WORLDEVENT_CLOSE_GVE_BATTLE = "WORLDEVENT_CLOSE_GVE_BATTLE"

-- 打开star宝箱
WorldEvent.WORLDEVENT_OPEN_STAR_BOXES = "WorldEvent.WORLDEVENT_OPEN_STAR_BOXES"

-- 打开额外宝箱
WorldEvent.WORLDEVENT_OPEN_EXTRA_BOXES = "WorldEvent.WORLDEVENT_OPEN_EXTRA_BOXES"

-- 试炼小红点状态
WorldEvent.WORLDEVENT_TRAIL_RED_POINT_UPDATE = "WorldEvent.WORLDEVENT_TRAIL_RED_POINT_UPDATE"
-- 竞技场小红点状态
WorldEvent.WORLDEVENT_PVP_RED_POINT_UPDATE = "WorldEvent.WORLDEVENT_PVP_RED_POINT_UPDATE"

-- PVE战斗胜利
WorldEvent.WORLDEVENT_PVE_BATTLE_WIN = "WorldEvent.WORLDEVENT_PVE_BATTLE_WIN"

-- 打开关卡明细界面
WorldEvent.WORLDEVENT_PVE_OPEN_LEVEL_VIEW = "WorldEvent.WORLDEVENT_PVE_OPEN_LEVEL_VIEW"

-- 关闭关卡明细界面
WorldEvent.WORLDEVENT_PVE_CLOSE_LEVEL_VIEW = "WorldEvent.WORLDEVENT_PVE_CLOSE_LEVEL_VIEW"

-- 初始化进入序章界面
WorldEvent.WORLDEVENT_PROLOGUE_VIEW = "WorldEvent.WORLDEVENT_PROLOGUE_VIEW"

-- 重置精英挑战次数
WorldEvent.WORLDEVENT_BUY_CHALLEGE_TIMES = "WorldEvent.WORLDEVENT_BUY_CHALLEGE_TIMES"

-- 首次通关
WorldEvent.WORLDEVENT_FIRST_PASS_RAID = "WorldEvent.WORLDEVENT_FIRST_PASS_RAID"
-- ============================= 六界事件 =============================
-- 切换章
WorldEvent.WORLDEVENT_SWTCH_STORY = "WorldEvent.WORLDEVENT_SWTCH_STORY"

-- 展示大地图
WorldEvent.WORLDEVENT_SHOW_MAIN_MAP = "WorldEvent.WORLDEVENT_SHOW_MAIN_MAP"

-- 展示缩略图
WorldEvent.WORLDEVENT_SHOW_AERIAL_MAP = "WorldEvent.WORLDEVENT_SHOW_AERIAL_MAP"

-- 更新地图内容
WorldEvent.WORLDEVENT_UPDATE_MAP_INFO = "WorldEvent.WORLDEVENT_UPDATE_MAP_INFO"

-- 更新主地图
WorldEvent.WORLDEVENT_UPDATE_MAIN_MAP = "WorldEvent.WORLDEVENT_UPDATE_MAIN_MAP"

-- 更新缩略图
WorldEvent.WORLDEVENT_UPDATE_AERIA_MAP = "WorldEvent.WORLDEVENT_UPDATE_AERIA_MAP"

-- 点击了npc
WorldEvent.WORLDEVENT_CLICK_ONE_NPC = "WorldEvent.WORLDEVENT_CLICK_ONE_NPC"

-- 自动点击当前npc
WorldEvent.WORLDEVENT_AUTO_CLICK_CUR_NPC = "WorldEvent.WORLDEVENT_AUTO_CLICK_CUR_NPC"

-- 点击了第三方玩家
WorldEvent.WORLDEVENT_CLICK_ONE_PLAYER = "WorldEvent.WORLDEVENT_CLICK_ONE_PLAYER"

-- 点击了地标
WorldEvent.WORLDEVENT_CLICK_ONE_SPACE = "WorldEvent.WORLDEVENT_CLICK_ONE_SPACE"

-- 进入地标(其他UI发送消息)
WorldEvent.WORLDEVENT_ENTER_ONE_SPACE = "WorldEvent.WORLDEVENT_ENTER_ONE_SPACE"

-- 靠近地标(其他UI发送消息)
WorldEvent.WORLDEVENT_NEAR_ONE_SPACE = "WorldEvent.WORLDEVENT_NEAR_ONE_SPACE"

-- 进入六界轶事场景中
WorldEvent.WORLDEVENT_ENTER_ONE_MISSION = "WorldEvent.WORLDEVENT_ENTER_ONE_MISSION"

-- 强制主角靠近npc
WorldEvent.WORLDEVENT_FORCE_CHAR_TO_NPC = "WorldEvent.WORLDEVENT_FORCE_CHAR_TO_NPC"

-- 关闭六界大地图
WorldEvent.WORLDEVENT_CLOSE_WORLD = "WorldEvent.WORLDEVENT_CLOSE_WORLD"

-- 关闭整个六界
WorldEvent.WORLDEVENT_CLOSE_WHOLE_WORLD = "WorldEvent.WORLDEVENT_CLOSE_WHOLE_WORLD"

-- 六界地图触摸事件
WorldEvent.WORLDEVENT_MAP_TOUCH = "WorldEvent.WORLDEVENT_MAP_TOUCH"

-- 六界地图UI层触摸事件
WorldEvent.WORLDEVENT_MAP_UI_TOUCH = "WorldEvent.WORLDEVENT_MAP_UI_TOUCH"

-- 更新npc
WorldEvent.WORLDEVENT_UPDATE_NPC_WHEN_TOP_VIEW = "WorldEvent.WORLDEVENT_UPDATE_NPC_WHEN_TOP_VIEW"

-- 获取在线玩家
WorldEvent.GET_ONLINE_PLAYER = "WorldEvent.GET_ONLINE_PLAYER"

-- 刷新在线玩家
WorldEvent.GET_ONLINE_PLAYER_AGAIN = "WorldEvent.GET_ONLINE_PLAYER_AGAIN"

-- 获取在线玩家成功
WorldEvent.GET_ONLINE_PLAYER_SUCCESS = "WorldEvent.GET_ONLINE_PLAYER_SUCCESS"

-- 刷新在线玩家成功
WorldEvent.GET_ONLINE_PLAYER_AGAIN_SUCCESS = "WorldEvent.GET_ONLINE_PLAYER_AGAIN_SUCCESS"

-- 六界主界面成为顶层界面
WorldEvent.WORLDEVENT_WORLD_MAIN_ON_TOPVIEW = "WorldEvent.WORLDEVENT_WORLD_MAIN_ON_TOPVIEW"
-- 六界主界面成为非顶层界面
WorldEvent.WORLDEVENT_WORLD_MAIN_ON_NOT_TOPVIEW = "WorldEvent.WORLDEVENT_WORLD_MAIN_ON_NOT_TOPVIEW"

-- 打开仙灵委托见面
WorldEvent.WORLDEVENT_OPEN_SHIJIAN_VIEW = "WorldEvent.WORLDEVENT_OPEN_SHIJIAN_VIEW"

--六界气泡需要变换
WorldEvent.BUBBLE_NEED_CHANGED = "BUBBLE_NEED_CHANGED"

--六初始化完成
WorldEvent.WORLD_UI_AND_BTN_FINISH = "WORLD_UI_AND_BTN_FINISH"


--点击追踪栏，剧情事件
WorldEvent.TOUCHTRIAK_ICON_PLOT = "TOUCHTRIAK_ICON_PLOT"



return WorldEvent
